Fix some small spelling errors
infi-nl/the-infi-way pull request #101
Opened 2023-11-03 15:46 UTC by rutgervanwilligen

2023-11-04 14:48 UTC, jeroenheijmans requested changes
Looks good, thanks! Only one small thing to tweak I think, the copyright year was intentionally 2022 (the year we first published this document, even though it was created privately in 2021 IIRC).

2023-11-04 14:48 UTC, jeroenheijmans commented on src/template.html
Copyright year (and/or date) should indicate the original creation time (the year in which you claimed copyright), so it can remain at 2022.

2023-11-06 08:07 UTC, rutgervanwilligen commented on src/template.html
Ah, okay! Change has been reverted ✅

2023-11-06 20:34 UTC, jeroenheijmans approved these changes

2023-11-06 20:34 UTC, merged